"use client";

import { useState, useEffect } from 'react';
import Link from 'next/link';
import { 
    FiArrowLeft, FiDownload, FiCalendar, 
    FiCheckCircle, FiClock, FiActivity, FiLayers,
    FiPieChart, FiBarChart2, FiGlobe, FiDatabase,
    FiTarget, FiBriefcase
} from 'react-icons/fi';
import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { toast } from 'sonner';

const BRAND = "rgb(151,0,3)";

export default function SuperAnalyticsDashboard() {
    const [loading, setLoading] = useState(true);
    const [data, setData] = useState<any>(null);
    const [selectedDate, setSelectedDate] = useState(() => {
        const d = new Date();
        return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
    });

    useEffect(() => {
        fetchData(selectedDate);
    }, [selectedDate]);

    const fetchData = async (date: string) => {
        setLoading(true);
        try {
            const res = await fetch(`/api/dashboard/admin/super-analytics?date=${date}`);
            const json = await res.json();
            if (json.success) {
                setData(json);
            } else {
                toast.error(json.error || "Failed to fetch analytics");
            }
        } catch (err) {
            toast.error("Error fetching data");
        }
        setLoading(false);
    };

    const generatePDF = () => {
        if (!data || !data.activities) {
            toast.error("No data available to download.");
            return;
        }

        try {
            const doc = new jsPDF('landscape');
            
            // Header Section
            doc.setFillColor(151, 0, 3); // BRAND color
            doc.rect(0, 0, doc.internal.pageSize.width, 35, 'F');
            
            doc.setTextColor(255, 255, 255);
            doc.setFontSize(24);
            doc.setFont("helvetica", "bold");
            doc.text("Super Admin Daily Activity Report", 14, 22);
            
            doc.setFontSize(11);
            doc.setFont("helvetica", "normal");
            doc.text(`Generated for Date: ${selectedDate}`, doc.internal.pageSize.width - 65, 22);

            // Summary Stats Section
            doc.setTextColor(33, 37, 41);
            doc.setFontSize(14);
            doc.setFont("helvetica", "bold");
            doc.text(`Daily Executive Summary`, 14, 50);
            
            doc.setFontSize(11);
            doc.setFont("helvetica", "normal");
            doc.text(`Total Activities: ${data.daily.total}`, 14, 60);
            doc.text(`Completed: ${data.daily.completed}`, 60, 60);
            doc.text(`Pending: ${data.daily.pending}`, 100, 60);
            doc.text(`Ongoing/Upcoming: ${data.daily.ongoing + data.daily.upcoming}`, 140, 60);
            
            doc.text(`SAC Clubs: ${data.daily.sac_count}`, 14, 68);
            doc.text(`DEPT Clubs: ${data.daily.dept_count}`, 60, 68);
            doc.text(`MHS Clubs: ${data.daily.mhs_count}`, 100, 68);

            // Table Data
            const tableData = data.activities.map((a: any) => [
                a.code,
                a.title,
                a.domain,
                a.dept_name || a.domain,
                a.dept_club,
                a.venue,
                `${a.start_time || '--:--'} to ${a.end_time || '--:--'}`,
                a.status.toUpperCase()
            ]);

            autoTable(doc, {
                startY: 80,
                head: [['Activity ID', 'Title', 'Domain', 'Department', 'Club Name', 'Venue', 'Timings', 'Status']],
                body: tableData,
                theme: 'striped',
                headStyles: { 
                    fillColor: [151, 0, 3],
                    textColor: [255, 255, 255],
                    fontStyle: 'bold',
                    halign: 'center'
                },
                bodyStyles: {
                    fontSize: 9,
                    valign: 'middle'
                },
                alternateRowStyles: { 
                    fillColor: [248, 249, 250] 
                },
                columnStyles: {
                    0: { cellWidth: 25, halign: 'center' }, // Activity ID
                    2: { cellWidth: 25, halign: 'center' }, // Domain
                    3: { cellWidth: 35 },                   // Department
                    7: { cellWidth: 25, halign: 'center', fontStyle: 'bold' } // Status
                },
                margin: { top: 15, right: 14, bottom: 15, left: 14 },
                didDrawPage: function (data) {
                    // Footer
                    const str = 'Page ' + (doc.internal as any).getNumberOfPages();
                    doc.setFontSize(8);
                    doc.setTextColor(128, 128, 128);
                    doc.text(str, data.settings.margin.left, doc.internal.pageSize.height - 10);
                    doc.text("Generated by KL University SAC Super Admin Dashboard", doc.internal.pageSize.width - data.settings.margin.right - 80, doc.internal.pageSize.height - 10);
                }
            });

            doc.save(`SuperAdmin_Activity_Report_${selectedDate}.pdf`);
            toast.success("PDF Report Downloaded successfully!");
        } catch (error) {
            console.error("PDF Generation Error:", error);
            toast.error("Failed to generate PDF report.");
        }
    };

    const getStatusColor = (status: string) => {
        switch (status) {
            case 'completed': return 'bg-emerald-50 text-emerald-700 border-emerald-200';
            case 'pending': return 'bg-red-50 text-red-700 border-red-200';
            case 'ongoing': return 'bg-blue-50 text-blue-700 border-blue-200';
            default: return 'bg-gray-50 text-gray-700 border-gray-200';
        }
    };

    const getStatusIcon = (status: string) => {
        switch (status) {
            case 'completed': return <FiCheckCircle className="inline mr-1" />;
            case 'pending': return <FiClock className="inline mr-1" />;
            case 'ongoing': return <FiActivity className="inline mr-1" />;
            default: return <FiCalendar className="inline mr-1" />;
        }
    };

    if (loading && !data) {
        return (
            <div className="flex items-center justify-center min-h-[60vh]">
                <div className="animate-spin rounded-full h-12 w-12 border-b-2" style={{ borderColor: BRAND }}></div>
            </div>
        );
    }

    return (
        <div className="max-w-7xl mx-auto space-y-8 pb-12">
            
            {/* Header Section */}
            <div className="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden relative">
                <div className="absolute top-0 left-0 w-1.5 h-full" style={{ backgroundColor: BRAND }}></div>
                <div className="p-6 md:p-8 flex flex-col md:flex-row justify-between items-start md:items-center gap-6">
                    <div>
                        <div className="flex items-center gap-4 mb-3">
                            <Link href="/dashboard/admin" className="p-2.5 bg-gray-50 rounded-full hover:bg-gray-100 transition-colors text-gray-500 hover:text-gray-900 border border-gray-200 shadow-sm">
                                <FiArrowLeft />
                            </Link>
                            <h1 className="text-3xl font-extrabold tracking-tight text-gray-900">Super Analytics</h1>
                        </div>
                        <p className="text-gray-500 text-sm ml-14 max-w-lg leading-relaxed">
                            Comprehensive executive overview of all student club activities, domains, and precise daily tracking insights.
                        </p>
                    </div>

                    <div className="flex flex-col sm:flex-row items-center gap-4 w-full md:w-auto ml-14 md:ml-0">
                        <div className="relative w-full sm:w-auto shadow-sm">
                            <FiCalendar className="absolute left-3.5 top-1/2 -translate-y-1/2 text-gray-400" />
                            <input 
                                type="date" 
                                value={selectedDate}
                                onChange={(e) => setSelectedDate(e.target.value)}
                                className="pl-11 pr-4 py-2.5 w-full bg-white border border-gray-200 rounded-xl text-sm font-semibold focus:outline-none focus:ring-2 focus:ring-red-900 focus:border-transparent transition-all"
                            />
                        </div>
                        <button 
                            onClick={generatePDF}
                            className="w-full sm:w-auto flex items-center justify-center gap-2.5 px-6 py-2.5 rounded-xl text-sm font-bold text-white shadow-md hover:shadow-lg transition-all active:scale-95"
                            style={{ backgroundColor: BRAND }}
                        >
                            <FiDownload size={16} />
                            Download Report
                        </button>
                    </div>
                </div>
            </div>

            {/* Overall Database Analytics */}
            <div>
                <h2 className="text-lg font-extrabold text-gray-900 mb-5 flex items-center gap-2.5 px-1">
                    <div className="p-2 bg-red-50 rounded-lg"><FiDatabase style={{ color: BRAND }} /></div> 
                    Overall Activity Master (All Time)
                </h2>
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-5">
                    <div className="bg-white p-6 rounded-2xl shadow-sm border border-gray-100 hover:shadow-md transition-all relative overflow-hidden group">
                        <div className="absolute -right-4 -top-4 opacity-5 transition-transform group-hover:scale-110">
                            <FiLayers size={100} />
                        </div>
                        <div className="flex items-center gap-3 mb-4 text-gray-500 relative z-10">
                            <div className="p-2.5 bg-gray-50 rounded-lg text-gray-700 border border-gray-200"><FiLayers size={18} /></div>
                            <span className="text-sm font-bold tracking-wide uppercase">Total Activities</span>
                        </div>
                        <div className="text-4xl font-black text-gray-900 relative z-10">{data?.overall?.total || 0}</div>
                    </div>
                    
                    <div className="bg-gradient-to-br from-blue-600 to-blue-800 p-6 rounded-2xl shadow-sm text-white hover:shadow-md transition-all relative overflow-hidden group">
                        <div className="absolute -right-4 -top-4 opacity-10 transition-transform group-hover:scale-110">
                            <FiGlobe size={100} />
                        </div>
                        <div className="flex items-center gap-3 mb-4 text-blue-100 relative z-10">
                            <div className="p-2.5 bg-white/20 rounded-lg text-white backdrop-blur-sm"><FiGlobe size={18} /></div>
                            <span className="text-sm font-bold tracking-wide uppercase">SAC Clubs</span>
                        </div>
                        <div className="text-4xl font-black relative z-10">{data?.overall?.sac_total || 0}</div>
                    </div>

                    <div className="bg-gradient-to-br from-purple-600 to-purple-800 p-6 rounded-2xl shadow-sm text-white hover:shadow-md transition-all relative overflow-hidden group">
                        <div className="absolute -right-4 -top-4 opacity-10 transition-transform group-hover:scale-110">
                            <FiBriefcase size={100} />
                        </div>
                        <div className="flex items-center gap-3 mb-4 text-purple-100 relative z-10">
                            <div className="p-2.5 bg-white/20 rounded-lg text-white backdrop-blur-sm"><FiBriefcase size={18} /></div>
                            <span className="text-sm font-bold tracking-wide uppercase">DEPT Clubs</span>
                        </div>
                        <div className="text-4xl font-black relative z-10">{data?.overall?.dept_total || 0}</div>
                    </div>

                    <div className="bg-gradient-to-br from-emerald-600 to-emerald-800 p-6 rounded-2xl shadow-sm text-white hover:shadow-md transition-all relative overflow-hidden group">
                        <div className="absolute -right-4 -top-4 opacity-10 transition-transform group-hover:scale-110">
                            <FiTarget size={100} />
                        </div>
                        <div className="flex items-center gap-3 mb-4 text-emerald-100 relative z-10">
                            <div className="p-2.5 bg-white/20 rounded-lg text-white backdrop-blur-sm"><FiTarget size={18} /></div>
                            <span className="text-sm font-bold tracking-wide uppercase">MHS Clubs</span>
                        </div>
                        <div className="text-4xl font-black relative z-10">{data?.overall?.mhs_total || 0}</div>
                    </div>
                </div>
            </div>

            {/* Daily Analytics */}
            <div>
                <h2 className="text-lg font-extrabold text-gray-900 mb-5 flex items-center gap-2.5 px-1">
                    <div className="p-2 bg-red-50 rounded-lg"><FiActivity style={{ color: BRAND }} /></div>
                    Daily Tracking <span className="text-gray-400 font-medium ml-1">({new Date(selectedDate).toLocaleDateString(undefined, { weekday: 'long', month: 'short', day: 'numeric' })})</span>
                </h2>
                
                <div className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden mb-6">
                    <div className="grid grid-cols-2 md:grid-cols-4 divide-x divide-y md:divide-y-0 divide-gray-100">
                        <div className="p-6 md:p-8 text-center hover:bg-gray-50 transition-colors">
                            <p className="text-xs font-bold text-gray-500 uppercase tracking-widest mb-2">Activities Today</p>
                            <p className="text-4xl font-black text-gray-900">{data?.daily?.total || 0}</p>
                        </div>
                        <div className="p-6 md:p-8 text-center hover:bg-gray-50 transition-colors">
                            <p className="text-xs font-bold text-emerald-600 uppercase tracking-widest mb-2">Completed</p>
                            <p className="text-4xl font-black text-emerald-600">{data?.daily?.completed || 0}</p>
                        </div>
                        <div className="p-6 md:p-8 text-center hover:bg-gray-50 transition-colors">
                            <p className="text-xs font-bold text-red-600 uppercase tracking-widest mb-2">Pending Action</p>
                            <p className="text-4xl font-black text-red-600">{data?.daily?.pending || 0}</p>
                        </div>
                        <div className="p-6 md:p-8 text-center hover:bg-gray-50 transition-colors">
                            <p className="text-xs font-bold text-blue-600 uppercase tracking-widest mb-2">Ongoing/Upcoming</p>
                            <p className="text-4xl font-black text-blue-600">{(data?.daily?.ongoing || 0) + (data?.daily?.upcoming || 0)}</p>
                        </div>
                    </div>
                </div>

                <div className="bg-white rounded-2xl border border-gray-100 shadow-sm overflow-hidden">
                    <div className="p-6 border-b border-gray-100 bg-gray-50/50 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
                        <h3 className="font-extrabold text-gray-900 text-lg">Detailed Activity Breakdown</h3>
                        <div className="flex gap-2.5">
                            <span className="px-3 py-1.5 bg-blue-50 text-blue-700 text-xs font-bold rounded-lg border border-blue-100 shadow-sm">
                                SAC: {data?.daily?.sac_count || 0}
                            </span>
                            <span className="px-3 py-1.5 bg-purple-50 text-purple-700 text-xs font-bold rounded-lg border border-purple-100 shadow-sm">
                                DEPT: {data?.daily?.dept_count || 0}
                            </span>
                            <span className="px-3 py-1.5 bg-emerald-50 text-emerald-700 text-xs font-bold rounded-lg border border-emerald-100 shadow-sm">
                                MHS: {data?.daily?.mhs_count || 0}
                            </span>
                        </div>
                    </div>
                    
                    {loading ? (
                        <div className="p-16 text-center">
                            <div className="animate-spin rounded-full h-8 w-8 border-b-2 mx-auto mb-4" style={{ borderColor: BRAND }}></div>
                            <p className="text-gray-400 font-medium">Loading precise analytics data...</p>
                        </div>
                    ) : !data?.activities || data.activities.length === 0 ? (
                        <div className="p-20 flex flex-col items-center text-gray-400 gap-4">
                            <div className="p-4 bg-gray-50 rounded-full">
                                <FiCalendar size={40} className="text-gray-300" />
                            </div>
                            <p className="font-semibold text-gray-500 text-lg">No activities scheduled for this date.</p>
                            <p className="text-sm">Try selecting a different date from the calendar.</p>
                        </div>
                    ) : (
                        <div className="overflow-x-auto">
                            <table className="w-full text-left border-collapse">
                                <thead>
                                    <tr className="bg-gray-50 text-gray-500 text-xs font-bold uppercase tracking-wider border-b border-gray-200">
                                        <th className="p-5">Status</th>
                                        <th className="p-5">Timings</th>
                                        <th className="p-5">Domain</th>
                                        <th className="p-5">Department / Club Name</th>
                                        <th className="p-5">Activity Information</th>
                                        <th className="p-5">Location</th>
                                    </tr>
                                </thead>
                                <tbody className="divide-y divide-gray-100 text-sm">
                                    {data.activities.map((a: any, idx: number) => (
                                        <tr key={idx} className="hover:bg-red-50/10 transition-colors group">
                                            <td className="p-5 align-top">
                                                <span className={`inline-flex items-center px-3 py-1.5 rounded-lg text-xs font-bold uppercase tracking-wider border shadow-sm ${getStatusColor(a.status)}`}>
                                                    {getStatusIcon(a.status)}
                                                    {a.status}
                                                </span>
                                            </td>
                                            <td className="p-5 align-top font-semibold text-gray-900 whitespace-nowrap">
                                                {a.start_time ? a.start_time.substring(0, 5) : '--:--'}
                                                <br/>
                                                <span className="text-gray-500 text-xs font-medium">to {a.end_time ? a.end_time.substring(0, 5) : '--:--'}</span>
                                            </td>
                                            <td className="p-5 align-top">
                                                <div className="font-bold text-gray-900">{a.domain}</div>
                                                <div className="text-gray-400 text-xs font-mono mt-1 bg-gray-50 border border-gray-100 px-1.5 py-0.5 rounded inline-block">{a.code}</div>
                                            </td>
                                            <td className="p-5 align-top max-w-[220px]">
                                                <div className="font-bold text-gray-900 mb-1 leading-snug">{a.dept_name || a.domain}</div>
                                                <div className="text-gray-500 text-xs font-medium">{a.dept_club}</div>
                                            </td>
                                            <td className="p-5 align-top max-w-[250px]">
                                                <div className="font-bold text-gray-900 leading-snug">{a.title}</div>
                                            </td>
                                            <td className="p-5 align-top">
                                                <div className="text-gray-700 font-medium">{a.venue}</div>
                                            </td>
                                        </tr>
                                    ))}
                                </tbody>
                            </table>
                        </div>
                    )}
                </div>
            </div>

        </div>
    );
}
